### ISSUE TITLE
LTI Logging problem with SSO MiniOrange plugin

### ISSUE THREAD

**Issue by kk122345** [celtic-project/wordpress-lti-platform#1] opened 2022-06-23 06:35 UTC
Hi,

I install LTI tool plugin and created a platform to connect Moodle LMS. On Moodle, When we launch an external tool to login then LTI connection does not complete and return an error message `JWT Signature did not verify. Please Try Logging in again.`

When I enable debugging I found it redirecting to the MiniOrange plugin. I do not understand why it redirects to MiniOrange plugin.

The connection stops at this URL `https://xyz/?lti-tool` and receives id_token & state params at this endpoint.

When I deactivate the MiniOrange plugin, Then It is working perfectly. 

Please suggest to me a possible solution to fix this.

![Screenshot 2022-06-23 120254](https://user-images.githubusercontent.com/45210461/175233124-1833832e-a8d8-4cc8-8f52-61e7e53b7379.png)

![Screenshot 2022-06-23 120017](https://user-images.githubusercontent.com/45210461/175231179-0404e0fc-1931-4a4e-bed0-6c9d03411b25.png)

**Comment by spvickers** [comment] 2022-06-23 07:57
It looks like your issue applies to the LTI Tool plugin, and not the LTI Platform plugin hosted in this repository.  The MiniOrange plugin does not look like it is freely available, so I cannot seek to replicate your issue, but the error message does not appear to be generated by the LTI Tool plugin so I suspect the MiniOrange plugin is intercepting this request for some reason.

**Comment by spvickers** [comment] 2022-07-01 14:49
I shall close this issue for now.  If you still think the LTI Tool plugin is the cause of your issue, please open an issue in its repository at https://github.com/celtic-project/wordpress-lti.  Thanks.

**Closed as completed by spvickers** 2022-07-01 14:49 UTC
