### ISSUE TITLE
Custom Object Not Being Passed

### ISSUE THREAD

**Issue by sitehub2009** [celtic-project/wordpress-lti-platform#3] opened 2023-03-06 21:50 UTC
We are using the LTI Platform plugin to iframe into an LTI Tool using v1.3. We have authenticated and connected successfully, and we're using deeplinking which is now showing a popup when we create a new shortcode so we can select the proper course to show.

However, once it creates a shortcode, we are seeing an error that our custom parameters are incorrect. The error is generated out of the Tool. When we look at the logs from the tool, it shows no parameters were being sent in. I confirmed this with a Chrome Extension called "LTI Debugger". Even though Custom params are in our shortcode, they are not sending. 

Our deep linked shortcode looks like this (redacted)
`[lti-platform tool=XXXX id=ktafytls title="XXXX" url=XXXX custom="orderId=63ea6c4305733XXXX;productType=Course;product={"ProductType":"Course","CourseId":"XXXX","Title":"XXXX)","OrderId":"XXXX"}"]1[/lti-platform]
`

A redacted sample from the LTI Debugger is below:
```
payload":{
"https://purl.imsglobal.org/spec/lti/claim/context":{
"id":"XXXX"
"title":""
"type":[...]
}
"https://purl.imsglobal.org/spec/lti/claim/launch_presentation":{
"document_target":"embed"
}
"https://purl.imsglobal.org/spec/lti/claim/tool_platform":{
"product_family_code":"WordPress"
"version":"6.1.1"
"name":"XXXX"
"description":"XXXX"
"url":"XXXX"
"contact_email":"XXXX"
}
"https://purl.imsglobal.org/spec/lti/claim/resource_link":{
"id":"XXXX"
"title":"XXXX"
}
"sub":"1"
"email":"XXXX"
"https://purl.imsglobal.org/spec/lti/claim/roles":[
0:"http://purl.imsglobal.org/vocab/lis/v2/membership#Learner"
]
"https://purl.imsglobal.org/spec/lti/claim/version":"1.3.0"
"https://purl.imsglobal.org/spec/lti/claim/message_type":"LtiResourceLinkRequest"
"iss":"XXXX"
"aud":[
0:"XXXX"
]
"azp":"itprotv"
"https://purl.imsglobal.org/spec/lti/claim/deployment_id":"1"
"https://purl.imsglobal.org/spec/lti/claim/target_link_uri":"XXXX"
"nonce":"d-XXXX"
"iat":XXXX
"exp":XXXX
```

**Comment by spvickers** [comment] 2023-03-06 22:02
I suspect this is being caused by the inclusion of double quotes within the attribute value as well as marking its start and end.  Try either removing the double quotes at the start and end (as these are not required as you value does not contain any spaces) or encoding the double quotes as &quot; within the custom attribute value.

**Comment by sitehub2009** [comment] 2023-03-07 01:47
I'm trying to follow along but I'm a bit lost. Using my previous shortcode 
`[lti-platform tool=XXXX id=ktafytls title="XXXX" url=XXXX custom="orderId=63ea6c4305733XXXX;productType=Course;product={"ProductType":"Course","CourseId":"XXXX","Title":"XXXX)","OrderId":"XXXX"}"]1[/lti-platform] 
`

Are you instead suggesting
`[lti-platform tool=XXXX id=ktafytls title="XXXX" url=XXXX custom=orderId=63ea6c4305733XXXX;productType=Course;product={"ProductType":"Course","CourseId":"XXXX","Title":"XXXX)","OrderId":"XXXX"}]1[/lti-platform] 
`

If so, I just tested and got the same missing custom param error.

**Comment by spvickers** [comment] 2023-03-07 08:03
Sorry my other suggestion was not displayed as typed but treated as an HTML entity.  What it meant to suggest was to replace all the double quotes within the attribute value with their encoded form of &amp;quot;.

**Comment by sitehub2009** [comment] 2023-03-07 21:53
Without any quote marks, it sends it but it is read as an invaled custom param, when I add the " around each of the attributes, it doesn't send the custom string at all. When I surround them with the code &quot; I get the following: 

"https://purl.imsglobal.org/spec/lti/claim/custom":{
"producttype":""
"product":"{"
"quot":""
"_":""
"course":""
"courseid":""
"XXXXX":""
"orderid":""
"XXXXX"

**Comment by spvickers** [comment] 2023-03-07 23:23
Thanks for the checking this out.  It looks like the issue is that the WordPress method for parsing shortcode attributes does not like the double quotes or colons and when these characters are encoded the semicolons are treated as separators.  I have committed a quick fix which seems to resolve your example, but needs further testing.  For it to work I replaced the double quotes in the JSON with &amp;quot; and the colons with &amp;#58;.

**Comment by sitehub2009** [comment] 2023-03-07 23:54
I don't see a plugin update in WP - do i need to do something to test this version?

**Comment by spvickers** [comment] 2023-03-07 23:56
The change has only been committed to this repository at present pending further testing.

**Comment by sitehub2009** [comment] 2023-03-08 14:30
Okay, one more thing that appears to be a problem --- I'm sending orderId and productType as custom params as well and they are sending as orderid and producttype -- apparently my tool is case sensitive and no matter what this plugin seems to be forcing those to send lowercase.

**Comment by spvickers** [comment] 2023-03-08 17:23
Yes, the package converts all the custom parameter names to be consistent with the LTI 1.0/1.1/1.2 specs which only support lowercase letters and numbers.  I will update the code to send both versions when using LTI 1.3 which relaxes these requirements.

**Comment by sitehub2009** [comment] 2023-03-09 00:06
Awesome - let me know when I should try to test this. I used your repository version and got the attached error. 
![unnamed](https://user-images.githubusercontent.com/89103316/223881182-97f0fb1b-1647-4553-923e-ead2638fe5b7.png)

**Comment by spvickers** [comment] 2023-03-09 00:17
This error seems to be coming from the woocommerce plugin.  I suspect it does not occur when this plugin is deactivated.  I don't see how any of the code changes made here would have caused this - have you made any other changes to your system since it was last working (though not passing through your custom parameters correctly)?

**Comment by sitehub2009** [comment] 2023-03-10 01:50
We did not make any other changes, but I'm interested in your updates. I was able to get my params to send using the custom box in the settings (rather than adding them in the shortcode) but the lowercase issue is what is setting me back now. I'm like 99% there!

**Comment by spvickers** [comment] 2023-03-10 09:31
Are the changes I committed to resolve the lowercase issue not working for you?

**Comment by sitehub2009** [comment] 2023-03-10 14:26
I could not use your committed version - it broke my site so I had to restore the old one. I'd love to test it, though!

**Comment by spvickers** [comment] 2023-03-10 16:33
Which version are you using?  Are you able to just edit the code you have installed with the changes committed for this issue?  I do not think these changes should cause the error you reported from the woocommerce plugin.

**Comment by sitehub2009** [comment] 2023-03-10 17:01
Changing this file caused my site to crash: 
https://github.com/celtic-project/wordpress-lti-platform/blob/main/includes/class-lti-platform-platform.php

"There has been a critical error on this website. Please check your site admin email inbox for instructions."

**Comment by sitehub2009** [comment] 2023-03-10 17:20
Ok, I got the error to go away by re-doing my copy/paste. I must have missed something. My fault.
However, the custom params are not being sent again which I think is due to the " mark issue, still. 

"payload":{
"https://purl.imsglobal.org/spec/lti/claim/context":{...}
"https://purl.imsglobal.org/spec/lti/claim/launch_presentation":{...}
"https://purl.imsglobal.org/spec/lti/claim/tool_platform":{...}
"https://purl.imsglobal.org/spec/lti/claim/resource_link":{...}
"sub":"1"
"email":"XXX"
"https://purl.imsglobal.org/spec/lti/claim/roles":[...]
"https://purl.imsglobal.org/spec/lti/claim/ext":{...}
"https://purl.imsglobal.org/spec/lti/claim/version":"1.3.0"
"https://purl.imsglobal.org/spec/lti/claim/message_type":"LtiResourceLinkRequest"
"iss":"https://XXX.com"
"aud":[...]
"azp":"XXX"
"https://purl.imsglobal.org/spec/lti/claim/deployment_id":"1"
"https://purl.imsglobal.org/spec/lti/claim/target_link_uri":"XXX"
"nonce":"XXX"
"iat":1678468740
"exp":1678468800

**Comment by spvickers** [comment] 2023-03-10 17:23
Have you encoded the double quotes and colons in your attribute value?  Perhaps submit a copy here for checking.

**Comment by spvickers** [comment] 2023-03-10 17:23
Which version of the plugin do you have installed?

**Comment by sitehub2009** [comment] 2023-03-10 17:25
When I use the custom params in the back end settings, I can get it to work
![image](https://user-images.githubusercontent.com/89103316/224382162-935bda5f-9f3c-4b7a-b4b9-54062ee652c1.png)

But when I use the shortcode, it creates this
[lti-platform tool=XXX id=XXX title="XXX" url=XXX custom="orderId=XXXX;productType=Course;product={"ProductType":"Course","CourseId":"XXXXX","Title":"XXXXXX","OrderId":"XXXXXXX"}"]test[/lti-platform]

And that doesn't work. Should I be replacing the qutoes in the shortcode with &quot;

**Comment by spvickers** [comment] 2023-03-10 17:27
Yes, see my earlier note "For it to work I replaced the double quotes in the JSON with &amp;quot; and the colons with &amp;#58;.".

**Comment by sitehub2009** [comment] 2023-03-10 17:29
Aha! The below shortcode worked. 

[lti-platform tool=XX id=XXtitle="XXX" url=XXX custom="orderId=XXXX;productType=Course;product={&quot;ProductType&quot;:&quot;Course&quot;,&quot;CourseId&quot;:&quot;XXX&quot;,&quot;Title&quot;:&quot;XXX&quot;,&quot;OrderId&quot;:&quot;XXXX&quot;}"]test[/lti-platform]

**Comment by spvickers** [comment] 2023-03-10 18:07
I suspect the above shortcode is not shown as intended (just like my original reminder was not!).  Is this what you successfully used?

`[lti-platform tool=XX id=XXtitle="XXX" url=XXX custom="orderId=XXXX;productType=Course;product={&quot;ProductType&quot;&#58;&quot;Course&quot;,&quot;CourseId&quot;&#58;&quot;XXX&quot;,&quot;Title&quot;&#58;&quot;XXX&quot;,&quot;OrderId&quot;&#58;&quot;XXXX&quot;}"]test[/lti-platform]`

**Comment by sitehub2009** [comment] 2023-03-10 18:36
Yes

Sean McKay
Site Hub // Founder
585-738-1134

- Sent from Mobile

**Comment by spvickers** [comment] 2023-03-10 18:56
Thanks for confirming this.  In relation to the woocommerce issue, please can you confirm which version of the LTI Platform plugin you are using and what URL generated the error.  Thanks.

**Comment by spvickers** [comment] 2023-03-13 19:30
@sitehub2009, please can you confirm which version of this plugin is working for you so that I can identify the code changes which are causing the incompatibility with the woocommerce plugin.  Thanks.

**Comment by sitehub2009** [comment] 2023-03-13 19:40
2.1.0 with the latest 2 commits you updated here.

**Comment by spvickers** [comment] 2023-03-13 19:42
Thanks @sitehub2009.

**Comment by spvickers** [comment] 2023-03-13 19:58
@sitehub2009, are you sure you have the 2.1.0 release installed?  I cannot see any code changes which would cause the issue you reported.  Do you see the "Role Mappings" section on the LTI Platform default settings page (.../wp-admin/options-general.php?page=lti-platform-settings)?

**Comment by sitehub2009** [comment] 2023-03-14 11:20
Yes I do see those settings.  And that's what it says in the plugin
details! How else can I check?. It appears to be the latest since no update
is available.


- Sent from Mobile

**Comment by spvickers** [comment] 2023-03-14 11:25
Thanks for confirming, it must be the latest release you are using then.  But I still do not see any commits since then which should cause the issue you reported.  Do you remember what you were doing when the error arose?

**Comment by spvickers** [comment] 2023-03-14 11:28
I also assume that you still have the woocommerce plugin activated on your server.

**Comment by sitehub2009** [comment] 2023-03-14 11:30
Correct. I think the error could have come from a poor job copy/pasting the
commits. Because it is now working as mentioned above.

I'm good at this point. Only annoying part is replacing the " with the
encoded version. The rest is working as expected with your commits.

**Comment by spvickers** [comment] 2023-03-14 11:34
OK, thanks.  Please open a new issue if it recurs.  I agree the encoding is annoying; I shall try to find a workaround for this but no promises!

**Closed as completed by spvickers** 2023-03-14 11:34 UTC
